## Signs a file
param([string] $file=$(throw "Please specify a filename."))
$cert = @(Get-ChildItem cert:\CurrentUser\My -codesigning)[0]
Set-AuthenticodeSignature $file $cert
# SIG # Begin signature block
# MIIFlAYJKoZIhvcNAQcCoIIFhTCCBYECAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUcfqVa1GUaGDvMBRcKQrOyTzk
# Jt6gggMiMIIDHjCCAgagAwIBAgIQdrQRV/d0wL1Ji38QPm+o4jANBgkqhkiG9w0B
# AQsFADAnMSUwIwYDVQQDDBxQb3dlclNoZWxsIENvZGUgU2lnbmluZyBDZXJ0MB4X
# DTIyMDkwMzExMzE1N1oXDTIzMDkwMzExNTE1N1owJzElMCMGA1UEAwwcUG93ZXJT
# aGVsbCBDb2RlIFNpZ25pbmcgQ2VydDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
# AQoCggEBAMVsDzacrNE3PEHol+ONZ+5BkcJFWn+Ic0lDKNXySnF1z2U1JjelkN4u
# 0kmg0F+Xw5DgH58sk/Oe8i96gLqQC3SixNSmbbEYGvHGDiwMZL9xsgBAtpzJUhx5
# UyRer0VDVhT/3ZZdfRn5ijTEfYS/yR0JG+46bMLLt1JFCm38y/jpoqPcNxkSdUqf
# K1Usxj7lMKd/uTDFi8LfgoDMQp9/lOimha9KpONizpK5NWHbWWGoWm8p7rm7NAbC
# ULmgV65htrVfrNrZjmVTa8nsyz6MJCp7Qp26pKzZ9S9cXhMqE0KKVFD1qcEyl/C/
# ScZxVUH6Blaze6lWGYNyiCJ61NyKAmECAwEAAaNGMEQwDgYDVR0PAQH/BAQDAgeA
# MBMGA1UdJQQMMAoGCCsGAQUFBwMDMB0GA1UdDgQWBBQDcNPeXOpDJ5jecnFazFx5
# 0yjerTANBgkqhkiG9w0BAQsFAAOCAQEADmZ1ImTh8M6NsK0IaVNkpiacTG9/8LQ9
# TsvxfkOillXSpF7wakXbBVdLqypnghJy+StXRAmU+tFp7efRKQKdFrIzEwUeC0HI
# fi3LfCVBbwPfwZ/fP2lnGzUjwl3dw4JJvk4bYatV6fvA+l6HoJlFdup5LNlrI74K
# dVF8EoOqAitJCw9S1nsDSDmz81jLfe48mFraNhMdTJfvrAFeTGdAlCj9wTJq5PsU
# RL98/+TjLMW5BVEYtV2bXAoieUvIP6bzYjhHnqSEI5ORwbbLlDw67J1V+yjrddyE
# ReNvfUNaYBgvEJ4+jxBM5Ywp3Pd7SywporufL2Tl+pqBQoCkc8+QWjGCAdwwggHY
# AgEBMDswJzElMCMGA1UEAwwcUG93ZXJTaGVsbCBDb2RlIFNpZ25pbmcgQ2VydAIQ
# drQRV/d0wL1Ji38QPm+o4jAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAig
# AoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgEL
# MQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUg6Gejd/Vr6lC36eex24/
# 9KqK/hgwDQYJKoZIhvcNAQEBBQAEggEABN4Zid/dJ49I4oYSszzASh1PSXTMfl/u
# oomrJttF0OFfFgEX3oPHgEeOXUYiegXI8laSU0N4vvV55fre+XlmA2uiRvbMcbJf
# mnpCeJ9ToM0B/Bps07RNxz2cE1GW32khlQov4OiYzM6M8UxHB5p3KJkNPQAb8jjw
# o5ZPrcJPxxh36LLZD292aKEz6Be3+orY1UJlf8KfkjB72VTCjoCjk7i2YnDOFr5w
# bZQCA1ST82H4KVx/XeBB2+HizIlUKKNFZncz02rSqkmOfyJAVmJYhm+mIk5unMuW
# As/XKUJBKCjAI9yo5/Ufeq4ddgs61Xlw2041kULdKk77c2Zwjvmshw==
# SIG # End signature block
